version: "{build}"

# Avoid build failure caused by the spotless plugin
init:
  - git config --global core.autocrlf true

# Build artifacts
build_script:
  - gradlew.bat assemble --stacktrace

# Verify artifacts
test_script:
  - gradlew.bat check -x integTest --stacktrace

# Branches to build
branches:
  only:
    - master

# Preserve dependencies between builds
cache:
  - C:\Users\appveyor\.gradle

# Environment settings
environment:
  matrix:
  # jdk 1.8
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  # jdk 11
  - JAVA_HOME: C:\Program Files\Java\jdk11
  # jdk 12
  - JAVA_HOME: C:\Program Files\Java\jdk12
  # jdk 13
  - JAVA_HOME: C:\Program Files\Java\jdk13

# Failing jobs settings
matrix:
  # Immediately finish build once one of the jobs fails
  fast_finish: true

on_failure:
  - cmd: set
  - cmd: type "%APPVEYOR_BUILD_FOLDER%\jodconverter-cli\build\tmp\javadoc\javadoc.options"
  - cmd: type "%APPVEYOR_BUILD_FOLDER%\jodconverter-core\build\tmp\javadoc\javadoc.options"
  - cmd: type "%APPVEYOR_BUILD_FOLDER%\jodconverter-local\build\tmp\javadoc\javadoc.options"
  - cmd: type "%APPVEYOR_BUILD_FOLDER%\jodconverter-online\build\tmp\javadoc\javadoc.options"
  - cmd: type "%APPVEYOR_BUILD_FOLDER%\jodconverter-spring\build\tmp\javadoc\javadoc.options"
  - cmd: type "%APPVEYOR_BUILD_FOLDER%\jodconverter-spring-boot-starter\build\tmp\javadoc\javadoc.options"
